# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    contact_repository:
        class:      AppBundle\Repository\ContactRepository
        factory:    ["@doctrine.orm.entity_manager", getRepository]
        arguments:  [AppBundle\Entity\Contact]

    address_repository:
        class:      AppBundle\Repository\AddressRepository
        factory:    ["@doctrine.orm.entity_manager", getRepository]
        arguments:  [AppBundle\Entity\Address]

    api.json_request_listener:
        class: AppBundle\EventListener\JsonRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
